### ISSUE TITLE
The exporter can fail unexpectedly if is queried before collecting information the first time

### ISSUE THREAD

**Issue by martonivan** [ngosang/restic-exporter#28]
2024-03-25 09:59:06 INFO     It could take a while if the repository is remote.
2024-03-25 09:59:59 ERROR    Unable to collect metrics from Restic. Error: Error executing restic snapshot command. Exit code: -9
Traceback (most recent call last):
  File "/restic-exporter.py", line 226, in <module>
    prometheus_client.core.REGISTRY.register(collector)
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/restic-exporter.py", line 66, in collect
    check_success.add_metric([], self.metrics["check_success"])
                                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'check_success'

**Comment by ngosang** [comment]
The Restic repository/server must be ready before starting this exporter.
